### ISSUE TITLE
Add method to refresh cache

### ISSUE THREAD

**Issue by cmoralesweb** [ablunier/laravel-database#2]
Something like 
``` $this->productRepository->refreshCache()->getLatestFavorites($this->loggedUser->id, 4)```

Right now, it's not possible to forget a specific query, either you use the cache, or you skip it every time (with ```skipCache()```method.

**Comment by ablunier** [comment]
Done & released on version 1.2.1

**Comment by ablunier** [comment]
https://github.com/ablunier/laravel-database/releases/tag/v1.2.1
